/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type PropertyDependenciesExample = (
  | ({type: "user"} & {
      name: string;
      [k: string]: unknown;
    })
  | ({type: "admin"} & {
      name: string;
      age?: number;
      permissions: string[];
      [k: string]: unknown;
    })
) & {
  type: "user" | "admin";
  name?: string;
  permissions?: string[];
  email?: string;
  [k: string]: unknown;
};
