/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export type MultiplePropertyDependenciesExample = (
  | ({platform: "web"} & {
      framework: "react" | "vue" | "angular";
      language: "typescript" | "javascript";
      [k: string]: unknown;
    })
  | ({platform: "mobile"} & {
      framework: "react-native" | "flutter";
      [k: string]: unknown;
    })
) & {
  platform: "web" | "mobile";
  framework?: "react" | "vue" | "angular" | "react-native" | "flutter";
  language?: "typescript" | "javascript";
  [k: string]: unknown;
};
