/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface RealWorld {
  subjects:
    | ({type: "byId"} & {
        type: "byId";
        visitId?: string;
        patientId?: string;
        caregiverId?: string;
      })
    | ({type: "manual"} & {
        type: "manual";
        visitStartTime?: string;
        visitEndTime?: string;
        caregiverName?: string;
        patientName?: string;
      });
  status?:
    | ({type: "open"} & {
        type: "open";
      })
    | ({type: "resolved"} & {
        type: "resolved";
      })
    | ({type: "transferred_to_agency"} & {
        type: "transferred_to_agency";
      })
    | ({type: "cancelled"} & {
        type: "cancelled";
        reason:
          | ({type: "duplicate"} & {
              type: "duplicate";
              duplicateOf?: string;
            })
          | ({type: "other"} & {
              type: "other";
              reason: string;
            });
      });
  currentlyWorkedOnBy?: {
    type: "person_profile" | "service_profile";
    id: string;
  }[];
  associatedPhoneNumbers?: string[];
}
